# These rules attempt to imbue cardinality into the variable names

Rules = {
    'adjective*': [nil, :'adjective+'],
    'adjective+': [:'adjective', [:'adjective', :'adjective'], [:'adjective', :'adjective', :'adjective']],
    'adjective': Lexicon['adjectives'],
    'but': ['taso'],
    'but?': [nil, :'but'],
    'fives': [nil, 'luka', ['luka', 'luka'], ['luka', 'luka', 'luka']],
    'genitive*': [nil, :'genitive+'],
    'genitive+': [['pi', :'noun', :'adjective+'], ['pi', :'noun', :'adjective+', 'pi', :'noun', :'adjective+'], ['pi', :'noun', :'adjective+', 'pi', :'noun', :'adjective+', 'pi', :'noun', :'adjective+']],
    'hundred*': [nil, :'hundred+'],
    'hundred+': ['ali', ['ali', 'ali'], ['ali', 'ali', 'ali']],
    'invocation': [['kon', 'Lawakasi', 'o']],
    'noun': Lexicon['nouns'],
    'noun phrase': [[:'noun', :'adjective*', :'genitive*', :'ordinal?']],
    'number': [[:'hundred*', :'twenties', :'fives', :'twos', :'ones']],
    'ones': [nil, 'wan'],
    'ordinal': [['nanpa', :'number']],
    'ordinal?': [nil, :'ordinal'],
    'pre-verb': Lexicon['pre-verbs'],
    'pre-verb?': [nil, :'pre-verb'],
    'precondition': [['tenpo', :'adjective*', :'genitive*', 'la'], ['ken', 'la'], [:'sentence', 'la']],
    'precondition?': [nil, :'precondition'],
    'predicate': [['pi', :'noun phrase'], :'prepositional phrase', [:'noun phrase', :'prepositional phrase?'], [:'verb phrase', :'prepositional phrase?']],
    'preposition': Lexicon['prepositions'],
    'prepositional phrase': [[:'preposition', :'noun phrase']],
    'prepositional phrase?': [nil, :'prepositional phrase'],
    'sentence*': [nil, :'sentence+'],
    'sentence+': [:'sentence', [:'sentence', :'sentence'], [:'sentence', :'sentence', :'sentence']],
    'sentence': [[:'but?', :'precondition?', :'subject', :'predicate', :'still?', '.']],
    'spell': [[:'invocation', :'predicate', :'terminator'], [:'invocation', '!', :'sentence*', :'terminator']],
    'still': ['kin'],
    'still?': [nil, :'still'],
    'subject': ['mi', [:'noun phrase', 'li']],
    'terminator': [:'yield?', 'a', '!'],
    'twenties': [nil, 'mute', ['mute', 'mute'], ['mute', 'mute', 'mute'], ['mute', 'mute', 'mute', 'mute']],
    'twos': ['tu', ['tu', 'tu']],
    'verb': Lexicon['verbs'],
    'verb phrase': [[:'pre-verb?', :'verb', :'adjective*'], [:'pre-verb?', :'verb', :'adjective*', 'e', :'noun phrase', :'prepositional phrase?']],
    'word': Lexicon.values.flatten.uniq,
    'word+': [:'word', [:'word', :'word'], [:'word', :'word', :'word']],
    'yield': [['mu', :'word+']],
    'yield?': [nil, :'yield']
}